In [1]:
# Librerías
import pandas as pd
import plotly.graph_objects as go

# Módulos
from Funciones.Buscar_cometa import buscar_cometa
from Funciones.Envolvente_superior_inferior import envolvente_superior_inferior
from Funciones.Envolvente_superior_inferior_archivos import envolvente_superior_inferior_archivos
from Funciones.Generar_grafica import generar_grafica

In [2]:
# Panel de control
nombre_del_cometa = '2212'
fecha_inicial = '1990-06-01'

In [3]:
buscar_cometa(nombre_del_cometa)

✅ Conectado a internet.
----------------------------------------
⌛ Conectando con la base de datos [COBS lista de Cometas].
✅ Base de datos actualizada [COBS lista de Cometas].
🛑 No hay coincidencias para: 2212, en la base de datos (COBS).

In [4]:
# Base de datos
bases_de_datos_cobs = envolvente_superior_inferior(nombre_del_cometa, fecha_inicial)

✅ Conectado a internet.
----------------------------------------
⌛ Conectando con la base de datos [COBS lista de Cometas].
✅ Base de datos actualizada [COBS lista de Cometas].
🛑 El cometa buscado, 2212, no se encuentra en la base de datos.

In [5]:
tipo_de_grafica = '1' 
generar_grafica(tipo_de_grafica, nombre_del_cometa, bases_de_datos_cobs)

TypeError: 'NoneType' object is not subscriptable

In [ ]:
# Cargar archivo con los datos del MPC
datos_mpc_df = pd.read_parquet('Archivos/2525_OStein_MPC.parquet')
datos_mpc_df

       obs_date  magnitude
0    1939-02-21      14.40
1    1953-09-07      14.40
2    1959-10-29      15.60
3    1959-10-29      15.60
4    1959-10-29      15.60
...         ...        ...
6988 2025-05-24      16.14
6989 2025-05-24      16.47
6990 2025-05-24      16.43
6991 2025-05-24      16.40
6992 2025-05-24      16.45

[6993 rows x 2 columns]

In [ ]:
datos_mpc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6993 entries, 0 to 6992
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   obs_date   6993 non-null   datetime64[ns]
 1   magnitude  6993 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 109.4 KB

In [ ]:
# bases_de_datos_mpc =  envolvente_superior_inferior_archivos(nombre_del_cometa, datos_mpc_df)
bases_de_datos_mpc =  envolvente_superior_inferior_archivos('2525', datos_mpc_df)

✅ Conectado a internet.
----------------------------------------

TypeError: descargar_efemerides() missing 1 required positional argument: 'curva_de_luz_cruda_df'

In [ ]:
tipo_de_grafica = '7' 
generar_grafica(tipo_de_grafica, nombre_del_cometa, bases_de_datos_mpc)

In [ ]:
tipo_de_grafica = '7' 
generar_grafica(tipo_de_grafica, nombre_del_cometa, bases_de_datos_mpc)

In [ ]:
bases_de_datos_mpc[1]

       obs_date  magnitude  delta      r  phase  magnitud_reducida  delta_t
0    1978-10-09      14.50  0.501  1.470   16.2          15.164225   -16211
1    1978-10-09      14.00  0.501  1.470   16.2          14.664225   -16211
2    1978-10-10      14.00  0.517  1.483   16.7          14.576842   -16210
3    1978-10-24      16.50  0.770  1.661   22.5          15.965698   -16196
4    1978-11-20      18.00  1.331  1.969   27.0          15.907881   -16169
...         ...        ...    ...    ...    ...                ...      ...
3605 2025-01-04      19.32  3.252  3.908   11.8          14.489475      678
3606 2025-02-26      20.01  3.984  3.806   14.4          14.176059      731
3607 2025-02-26      20.08  3.984  3.806   14.4          14.226059      731
3608 2025-02-26      20.13  3.984  3.806   14.4          14.216059      731
3609 2025-02-26      20.12  3.984  3.806   14.4                NaN      731

[3610 rows x 7 columns]

In [ ]:
# curva_cruda_cobs_df = bases_de_datos_cobs[1]
# envolvente_cobs_df = bases_de_datos_cobs[2] 
# nucleo_cobs_df = bases_de_datos_cobs[3]

curva_reducida_mpc_df = bases_de_datos_mpc[1] 
envolvente_mpc_df = bases_de_datos_mpc[2] 
nucleo_mpc_df = bases_de_datos_mpc[3]

In [ ]:
fig = go.Figure()
    
# fig.add_trace(go.Scatter(x=curva_cruda_cobs_df.obs_date, 
#         y=curva_cruda_cobs_df.magnitud_reducida, mode='markers',
#         name='Cruda_Cobs', 
#         marker=dict(color='#fa04f6', line=dict(width=1, color='DarkSlateGrey'))))

# fig.add_trace(go.Scatter(x=envolvente_cobs_df.obs_date, 
#         y=envolvente_cobs_df.promedio_movil, mode='markers',
#         name='Envolvente_Cobs', 
#         marker=dict(color='yellow', line=dict(width=1, color='DarkSlateGrey'))))

# fig.add_trace(go.Scatter(x=nucleo_cobs_df.obs_date, 
#         y=nucleo_cobs_df.promedio_movil, mode='markers',
#         name='Nucleo_Cobs', 
#         marker=dict(color='red', line=dict(width=1, color='DarkSlateGrey'))))

fig.add_trace(go.Scatter(x=curva_reducida_mpc_df.delta_t, 
        y=curva_reducida_mpc_df.magnitud_reducida, mode='markers',
        name='Reducida_MPC', 
        marker=dict(color='#04ebfa', line=dict(width=1, color='DarkSlateGrey'))))

fig.add_trace(go.Scatter(x=envolvente_mpc_df.delta_t, 
        y=envolvente_mpc_df.promedio_movil, mode='markers',
        name='Envolvente_MPC', 
        marker=dict(color='#fa7004 ', line=dict(width=1, color='DarkSlateGrey'))))

fig.add_trace(go.Scatter(x=nucleo_mpc_df.delta_t, 
        y=nucleo_mpc_df.promedio_movil, mode='markers',
        name='Nucleo_MPC', 
        marker=dict(color='#fa045b', line=dict(width=1, color='DarkSlateGrey'))))

fig.update_layout(template='plotly_dark')
fig.update_yaxes(autorange="reversed")
fig.update_layout(template='plotly_dark', xaxis_title='t - Tq [d]', yaxis_title=r'm(1,1,0)', title = f'Lightcurve of comet {nombre_del_cometa}')
fig.show()