In [2]:
import pandas as pd
import plotly.express as px

In [3]:
cometa_df = pd.read_excel('Archivos/12P_MPC.xlsx')
cometa_df

,Date (UT),J2000 RA,J2000 Dec,Magn,Location,Ref
0,1883 10 01.81962,16 29 30.06,+58 34 05.9,NaN,276 – Plonsk,AN 108
1,1883 10 02.85018,16 30 01.84,+58 20 40.9,NaN,276 – Plonsk,AN 108
2,1883 10 06.78805,16 32 32.55,+57 30 21.6,NaN,276 – Plonsk,AN 108
3,1883 10 30.74750,17 03 19.81,+52 49 06.5,NaN,276 – Plonsk,AN 108
4,1883 11 20.90579,17 56 42.17,+49 02 36.8,NaN,007 – Paris,BA 01
...,...,...,...,...,...,...
8300,2025 02 09.33825,17 08 38.10,-49 24 11.1,16.4 V,"I47 – Pierre Auger Observatory, Malargue",MPC 181621
8301,2025 02 22.339306,17 14 46.987,-49 54 54.61,18.29 o,"W68 – ATLAS Chile, Rio Hurtado",MPC 181621
8302,2025 02 22.342511,17 14 47.210,-49 54 56.05,18.35 o,"W68 – ATLAS Chile, Rio Hurtado",MPC 181621
8303,2025 02 22.360337,17 14 47.568,-49 54 57.53,18.16 o,"W68 – ATLAS Chile, Rio Hurtado",MPC 181621
8304,2025 02 22.378268,17 14 47.774,-49 55 00.23,18.31 o,"W68 – ATLAS Chile, Rio Hurtado",MPC 181621

In [4]:
filas,columnas = cometa_df.shape
print(f'Registros: {filas}\nVariables: {columnas}')

Registros: 8305
Variables: 6

In [5]:
cometa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8305 entries, 0 to 8304
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date (UT)  8305 non-null   object
 1   J2000 RA   8305 non-null   object
 2   J2000 Dec  8305 non-null   object
 3   Magn       7688 non-null   object
 4   Location   8305 non-null   object
 5   Ref        8303 non-null   object
dtypes: object(6)
memory usage: 389.4+ KB

In [6]:
cometa_df.columns = cometa_df.columns.str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
cometa_df.sample(10)

,date_ut,j2000_ra,j2000_dec,magn,location,ref
4808,2023 11 03.77622,17 45 16.15,+41 26 49.0,11.6 G,"A98 – Observatory Mazzarot-1, Baran'",MPC 167179
3980,2023 10 06.79747,17 22 15.14,+45 50 29.3,13.7 G,C23 – Olmen,MPC 167171
2084,2023 08 07.891517,17 50 05.349,+55 09 46.50,16.4 r,M09 – Observatory Gromme - Oudsbergen,MPC 164798
377,2023 04 24.573875,19 36 19.982,+40 44 24.65,18.64 c,"T05 – ATLAS-HKO, Haleakala",MPC 163363
2960,2023 09 03.898778,17 23 15.194,+51 40 24.30,15.9 r,M09 – Observatory Gromme - Oudsbergen,MPC 164806
6405,2023 12 30.71257,19 33 09.72,+37 44 23.5,13.6 G,"G00 – AZM Martinsberg, Oed",MPC 169246
3734,2023 09 28.85568,17 19 29.27,+47 15 20.9,15.7 N,I88 – Fuensanta de Martos,MPC 167169
3824,2023 10 01.84411,17 20 19.07,+46 43 09.1,15.2 G,"L63 – HOB Observatory, Capraia Fiorentina",MPC 167170
3449,2023 09 19.253226,17 18 36.158,+48 59 34.66,15.87 c,"T05 – ATLAS-HKO, Haleakala",MPC 167166
3426,2023 09 18.73160,17 18 38.14,+49 05 12.4,16.4 N,193 – Sanglok,MPC 167166

In [7]:
cometa_df.magn = cometa_df.magn.str.extract(r'(\d+\.\d+)')
cometa_df.sample(10)

,date_ut,j2000_ra,j2000_dec,magn,location,ref
2826,2023 08 26.94647,17 28 43.92,+52 55 17.7,16.1,"J01 – Observatorio Cielo Profundo, Leon",MPC 164805
1219,2023 07 22.56807,18 15 19.90,+55 50 04.9,NaN,867 – Saji Observatory,MPC 172008
6671,2024 01 14.73326,20 18 27.17,+37 57 51.5,12.8,"A77 – Observatoire Chante-Perdrix, Dauban",MPC 169248
2472,2023 08 14.00487,17 42 03.634,+54 35 19.43,16.2,"I81 – Tarbatness Observatory, Portmahomack",MPC 164802
214,2022 08 02.91407,17 53 03.86,+33 17 11.9,21.6,"G00 – AZM Martinsberg, Oed",MPC 142091
7464,2024 02 25.76981,23 17 01.55,+36 33 11.7,11.1,M18 – Koeditz,MPC 171476
8170,2024 06 20.43327,07 06 26.58,-30 38 12.9,11.5,"P14 – Nedlands Observatory, Perth",MPC 174257
137,1954 08 06.94373,09 42 37.82,-37 55 49.4,NaN,822 – Cordoba,CC 01
3825,2023 10 01.84910,17 20 19.16,+46 43 05.9,16.2,M14 – Schiaparelli Gallarate Station,MPC 167170
3644,2023 09 25.15051,17 18 49.06,+47 55 31.4,15.5,V21 – Cewanee Observatory at DSNM,MPC 167168

In [8]:
cometa_df['magn'] = pd.to_numeric(cometa_df.magn)
cometa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8305 entries, 0 to 8304
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date_ut    8305 non-null   object
 1   j2000_ra   8305 non-null   object
 2   j2000_dec  8305 non-null   object
 3   magn       7687 non-null   float64
 4   location   8305 non-null   object
 5   ref        8303 non-null   object
dtypes: float64(1), object(5)
memory usage: 389.4+ KB

In [9]:
cometa_filtrado_df = cometa_df[cometa_df.magn > 0].copy()
cometa_filtrado_df

,date_ut,j2000_ra,j2000_dec,magn,location,ref
141,2020 06 10.39794,18 04 12.24,+20 53 53.1,22.80,G37 – Lowell Discovery Telescope,MPC 123527
142,2020 06 10.40191,18 04 12.14,+20 53 53.1,22.70,G37 – Lowell Discovery Telescope,MPC 123527
143,2020 06 10.44291,18 04 11.21,+20 53 55.9,23.20,G37 – Lowell Discovery Telescope,MPC 123527
144,2020 06 17.31258,18 01 46.05,+21 01 28.6,24.00,G37 – Lowell Discovery Telescope,MPC 123527
145,2020 06 17.31624,18 01 45.96,+21 01 28.8,24.00,G37 – Lowell Discovery Telescope,MPC 123527
...,...,...,...,...,...,...
8300,2025 02 09.33825,17 08 38.10,-49 24 11.1,16.40,"I47 – Pierre Auger Observatory, Malargue",MPC 181621
8301,2025 02 22.339306,17 14 46.987,-49 54 54.61,18.29,"W68 – ATLAS Chile, Rio Hurtado",MPC 181621
8302,2025 02 22.342511,17 14 47.210,-49 54 56.05,18.35,"W68 – ATLAS Chile, Rio Hurtado",MPC 181621
8303,2025 02 22.360337,17 14 47.568,-49 54 57.53,18.16,"W68 – ATLAS Chile, Rio Hurtado",MPC 181621
8304,2025 02 22.378268,17 14 47.774,-49 55 00.23,18.31,"W68 – ATLAS Chile, Rio Hurtado",MPC 181621

In [10]:
cometa_dias_df = cometa_filtrado_df.date_ut.str.extract(r'(\d+\.\d+)')
cometa_dias_df = pd.to_numeric(cometa_dias_df[0])

cometa_procesado_df = pd.DataFrame()

cometa_procesado_df['obs_date'] = cometa_filtrado_df.date_ut.str.extract(r'(\d+ \d+)') 
cometa_procesado_df.obs_date = cometa_procesado_df.obs_date.str.replace(' ', '-')
cometa_procesado_df.obs_date = cometa_procesado_df.obs_date  + '-' + cometa_dias_df.apply(lambda dato: str(int(dato)))
cometa_procesado_df.obs_date = pd.to_datetime(pd.to_datetime(cometa_procesado_df.obs_date).dt.date)

cometa_procesado_df['magnitude'] = cometa_filtrado_df.magn

cometa_procesado_df.reset_index(inplace = True, drop= True)

cometa_procesado_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7687 entries, 0 to 7686
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   obs_date   7687 non-null   datetime64[ns]
 1   magnitude  7687 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 120.2 KB

In [11]:
cometa_procesado_df

       obs_date  magnitude
0    2020-06-10      22.80
1    2020-06-10      22.70
2    2020-06-10      23.20
3    2020-06-17      24.00
4    2020-06-17      24.00
...         ...        ...
7682 2025-02-09      16.40
7683 2025-02-22      18.29
7684 2025-02-22      18.35
7685 2025-02-22      18.16
7686 2025-02-22      18.31

[7687 rows x 2 columns]

In [12]:
fig = px.scatter(cometa_procesado_df, x='obs_date', y='magnitude', template= 'plotly_dark')
fig.update_yaxes(autorange="reversed")
fig.show()

In [13]:
cometa_procesado_df.to_parquet('Archivos/12P_Procesado_MPC.parquet', index = False)

In [14]:
import requests
import pandas as pd

response = requests.get("https://data.minorplanetcenter.net/api/get-obs", json={"desigs": ["12P"], "output_format":["OBS_DF"]})

if response.ok:
    mpc_obs_crude_df = pd.DataFrame(response.json()[0]['OBS_DF'])
    mpc_obs_crude_df

else:
    print("Error: ", response.status_code, response.content)

In [15]:
mpc_obs_proceed_df = pd.DataFrame()
mpc_obs_proceed_df['obs_date'] = mpc_obs_crude_df.obs80.str[15:19] + '-' + mpc_obs_crude_df.obs80.str[20:22] + '-' + mpc_obs_crude_df.obs80.str[23:25]
mpc_obs_proceed_df['magnitude'] = mpc_obs_crude_df.obs80.str[65:70].str.replace(' ', '')

mpc_obs_proceed_df.obs_date = pd.to_datetime(mpc_obs_proceed_df.obs_date)
mpc_obs_proceed_df.magnitude = pd.to_numeric(mpc_obs_proceed_df.magnitude)

mpc_obs_proceed_df

       obs_date  magnitude
0    1883-10-01        NaN
1    1883-10-02        NaN
2    1883-10-06        NaN
3    1883-10-30        NaN
4    1883-11-20        NaN
...         ...        ...
8349 2025-03-14      18.56
8350 2025-03-26      18.65
8351 2025-03-26      18.60
8352 2025-03-26      18.54
8353 2025-03-26      18.66

[8354 rows x 2 columns]

In [16]:
mpc_obs_proceed_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8354 entries, 0 to 8353
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   obs_date   8354 non-null   datetime64[ns]
 1   magnitude  7702 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 130.7 KB

In [45]:
# mpc_obs_filtered_df.magnitude.plot(kind='box')
px.box(mpc_obs_proceed_df, y='magnitude', template= 'plotly_dark')

In [ ]:
q1 = mpc_obs_proceed_df['magnitude'].quantile(0.25)
q3 = mpc_obs_proceed_df['magnitude'].quantile(0.75)

IQR = q3 - q1 

limite_inferior = q1 - 2.5 * IQR
limite_superior = q3 + 2.5 * IQR

# Filtrar los outliers
mpc_obs_filtered_df = mpc_obs_proceed_df[(mpc_obs_proceed_df['magnitude'] >= limite_inferior) & (mpc_obs_proceed_df['magnitude'] <= limite_superior)]

px.box(mpc_obs_filtered_df, y='magnitude', template= 'plotly_dark')

In [44]:
fig = px.scatter(mpc_obs_filtered_df, x='obs_date', y='magnitude', template= 'plotly_dark')
fig.update_yaxes(autorange="reversed")
fig.show()